### ISSUE TITLE
Site:https://www.tuning-links.com[Feature]

### ISSUE THREAD

**Issue by mrick01** [maned3v/memht#1]
Hello, Do you have the site https://www.tuning-links.com, you are indicated at the bottom of the site, can you update an email address which sends in http to put in https? I tried to connect but the catpcha the image is buggy impossible to connect to his account or to be able to modify

Thank
Franck

**Comment by maned3v** [comment]
> Hello, Do you have the site https://www.tuning-links.com, you are indicated at the bottom of the site, can you update an email address which sends in http to put in https? I tried to connect but the catpcha the image is buggy impossible to connect to his account or to be able to modify
> 
> Thank
> Franck

Hi Franck

I'm the developer of the CMS but i have no connection with the actual website you cited. I'm sorry but i can't help you.

**Comment by mrick01** [comment]
Hi, 

You do not have a contact email address, because it is impossible to send a message on the site or an idea to circumvent the image of the catpcha which is impossible to read

**Comment by maned3v** [comment]
> Hi, 
> 
> You do not have a contact email address, because it is impossible to send a message on the site or an idea to circumvent the image of the catpcha which is impossible to read
> 
> 

Are you the website owner? If so, you can disable the captcha in the config file, or you could upgrade your website to the last version, you'll solve your problems either way, else i cannot fix it since i have no access to it because it's not mine 😊

**Comment by mrick01** [comment]
Hi, No it's not my site, but my site is indicated as a link in the site and the link is in http, it's not good for backlinks, I wanted to change to https

**Comment by mrick01** [comment]
Anyhow, thanks for your help

**Comment by maned3v** [comment]
> Anyhow, thanks for your help
> 

Sorry i couldn't help more 🤷🏻
