### ISSUE TITLE
[Vuln] sXSS in Article comments

### ISSUE THREAD

**Issue by ShawRo0t** [maned3v/memht#2]
**Vulnerability Description**
Stored attacks are those where the injected script is permanently stored on the target servers.The victim then retrieves the malicious script from the server when it requests the stored information.

**Step To Reproduce**
Any article comments support bbcode.
When I leave a comment,input`[url]javascript:alert('test')[/url]`,it will cause XSS.
<img src=https://i.postimg.cc/zGz6xjR9/Video-2023-11-23-172420.gif>

**Impact**
An XSS attack allows an attacker to execute arbitrary JavaScript in the context of the attacked website and the attacked user. This can be abused to steal session cookies, perform requests in the name of the victim, or for phishing attacks.

**Comment by ShawRo0t** [comment]
AFFECTED  VERSION：<= 5.0.1.1

**Comment by maned3v** [comment]
Thank you for posting it Shaw, i'm retiring the project, nobody is using it anymore anyway :)
